### PR TITLE
Easier handling of skill levels by using defines instead of numbers

### PR DESCRIPTION
**Pull request by NeonKnightOA**
As requested in yquake2/yquake2#503, here's the adaptation.

### CODE REVIEW

**Comment by Yamagi** [comment]
I think you forgot to commit the header :)

```
===> Building game.so
gmake release/game.so
gmake[1]: Verzeichnis „/usr/home/yamagi/temp/yq2-zaero“ wird betreten
===> CC src/g_ai.c
src/g_ai.c:656:23: error: use of undeclared identifier 'SKILL_EASY'
                if (skill->value == SKILL_EASY && (rand()&3) )
                                    ^
src/g_ai.c:696:22: error: use of undeclared identifier 'SKILL_EASY'
        if (skill->value == SKILL_EASY)
                            ^
src/g_ai.c:698:27: error: use of undeclared identifier 'SKILL_HARD'
        else if (skill->value >= SKILL_HARD)
                                 ^
3 errors generated.
gmake[1]: *** [Makefile:162: build/src/g_ai.o] Fehler 1
gmake[1]: Verzeichnis „/usr/home/yamagi/temp/yq2-zaero“ wird verlassen
gmake: *** [Makefile:157: zaero] Fehler 2
```

**Comment by NeonKnightOA** [comment]
Ouch... -.-
Solving that in a moment. Sorry!

**Comment by NeonKnightOA** [comment]
There, problem solved.

**Comment by Yamagi** [comment]
Thank you!

**Pull request merged**
